<Project Sdk="Microsoft.NET.Sdk">
    
    <ItemGroup>
        <ProjectReference Include="..\..\dependency-injection\DandyDotnet.DependencyInjection.Abstractions\DandyDotnet.DependencyInjection.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>
