<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\DandyDotnet.Persistence.Sql.Migrations\DandyDotnet.Persistence.Sql.Migrations.csproj" />
        <ProjectReference Include="..\DandyDotnet.Persistence.Sql.SqlServer\DandyDotnet.Persistence.Sql.SqlServer.csproj" />
    </ItemGroup>

</Project>
