<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\persistence\DandyDotnet.Persistence.Sql.Migrations.Sqlite\DandyDotnet.Persistence.Sql.Migrations.Sqlite.csproj" />
    <ProjectReference Include="..\..\persistence\DandyDotnet.Persistence.Sql.Sqlite\DandyDotnet.Persistence.Sql.Sqlite.csproj" />
    <ProjectReference Include="..\DandyDotnet.Patterns.EventSourcing.Persistence.Sql\DandyDotnet.Patterns.EventSourcing.Persistence.Sql.csproj" />
  </ItemGroup>
</Project>
