<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\..\encoding\DandyDotnet.Encoding\DandyDotnet.Encoding.csproj" />
      <ProjectReference Include="..\..\serialization\DandyDotnet.Serialization\DandyDotnet.Serialization.csproj" />
      <ProjectReference Include="..\DandyDotnet.EventDrivenArchitecture.RabbitMQ.Producer.Abstractions\DandyDotnet.EventDrivenArchitecture.RabbitMQ.Producer.Abstractions.csproj" />
      <ProjectReference Include="..\DandyDotnet.EventDrivenArchitecture.RabbitMQ\DandyDotnet.EventDrivenArchitecture.RabbitMQ.csproj" />
    </ItemGroup>

</Project>
