<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <EnablePackageValidation>true</EnablePackageValidation>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PackageId>DandyDotnet.Patterns.Mediator.Queries.Abstractions</PackageId>
        <Authors>Nicolai Wolf</Authors>
        <Description>Mediator query abstractions.</Description>
        <RepositoryUrl>https://github.com/Nico1395/dandy-dotnet</RepositoryUrl>
        <PackageTags>Mediator, Mediator Pattern, Queries, CQRS</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../../../README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DandyDotnet.Patterns.Mediator.Abstractions\DandyDotnet.Patterns.Mediator.Abstractions.csproj" />
    </ItemGroup>

</Project>
