<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentMigrator.Runner.SQLite" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DandyDotnet.Patterns.EventSourcing.Sql\DandyDotnet.Patterns.EventSourcing.Sql.csproj" />
  </ItemGroup>
</Project>
