<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <EnablePackageValidation>true</EnablePackageValidation>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PackageId>DandyDotnet.EventDrivenArchitecture.RabbitMQ.Consumer.Abstractions</PackageId>
        <Authors>Nicolai Wolf</Authors>
        <Description>Abstractions for RabbitMQ consumers.</Description>
        <RepositoryUrl>https://github.com/Nico1395/dandy-dotnet</RepositoryUrl>
        <PackageTags>RabbitMQ, Message Broker</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../../../README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DandyDotnet.EventDrivenArchitecture.RabbitMQ.Abstractions\DandyDotnet.EventDrivenArchitecture.RabbitMQ.Abstractions.csproj" />
    </ItemGroup>

</Project>
