<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\..\persistence\DandyDotnet.Persistence.Sql.Migrations.Postgres\DandyDotnet.Persistence.Sql.Migrations.Postgres.csproj" />
      <ProjectReference Include="..\..\persistence\DandyDotnet.Persistence.Sql.Postgres\DandyDotnet.Persistence.Sql.Postgres.csproj" />
      <ProjectReference Include="..\DandyDotnet.Patterns.EventSourcing.Persistence.Sql\DandyDotnet.Patterns.EventSourcing.Persistence.Sql.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Npgsql" />
    </ItemGroup>

</Project>
