name: "Release packages"

on:
  release:
    types:
      - published

env:
  SLN: "./src/DandyDotnet.slnx"
  DOTNET_VERSION: "10.0.x"
  PACK_OUTPUT_DIRECTORY: "${{ github.workspace }}/output"
  NUGET_SOURCE_URL: "https://api.nuget.org/v3/index.json"
  NUGET_USER_NAME: ${{ secrets.NUGET_USER_NAME }}

jobs:
  publish:
    permissions:
      id-token: write
    
    name: "Pack and publish packages"
    runs-on: "ubuntu-latest"
    steps:
    - name: "Docker info"
      run: "docker info"
    
    - name: "Checkout"
      uses: "actions/checkout@v4"
      with:
        fetch-depth: 0

    - name: "Setup .NET"
      uses: "actions/setup-dotnet@v4"
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: "Restore dependencies"
      run: "dotnet restore ${{ env.SLN }}"

    - name: "Build project"
      run: "dotnet build ${{ env.SLN }} --no-restore --configuration Release"

    - name: "Run unit tests"
      run: "dotnet test ${{ env.SLN }} --no-restore --configuration Release"

    - name: "Pack project"
      run: |
        VERSION=${{ github.ref_name }}
        VERSION=${VERSION#v}
        dotnet pack ${{ env.SLN }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=$VERSION --output ${{ env.PACK_OUTPUT_DIRECTORY }}

    - name: NuGet login
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ env.NUGET_USER_NAME }}
          
    - name: "Push package"
      run: "dotnet nuget push '${{ env.PACK_OUTPUT_DIRECTORY }}/*.nupkg' -k ${{steps.login.outputs.NUGET_API_KEY}} -s ${{ env.NUGET_SOURCE_URL }} --skip-duplicate"

  docfx:
    permissions:
      contents: read
      pages: write
      id-token: write

    name: "Build and deploy DocFX"
    runs-on: ubuntu-latest
    needs: publish

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install DocFX
      run: dotnet tool install -g docfx

    - name: Build documentation
      working-directory: docfx
      run: docfx docfx.json

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docfx/_site

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
