<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <EnablePackageValidation>true</EnablePackageValidation>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PackageId>DandyDotnet.Patterns.EventSourcing</PackageId>
        <Authors>Nicolai Wolf</Authors>
        <Description>Implementations of abstractions for event sourcing and configuration API.</Description>
        <RepositoryUrl>https://github.com/Nico1395/dandy-dotnet</RepositoryUrl>
        <PackageTags>Event Sourcing</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../../../README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Dapper" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Hosting" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\dependency-injection\DandyDotnet.DependencyInjection\DandyDotnet.DependencyInjection.csproj" />
      <ProjectReference Include="..\..\serialization\DandyDotnet.Serialization.Abstractions\DandyDotnet.Serialization.Abstractions.csproj" />
      <ProjectReference Include="..\DandyDotnet.Patterns.EventSourcing.Abstractions\DandyDotnet.Patterns.EventSourcing.Abstractions.csproj" />
    </ItemGroup>

</Project>
